apiVersion: v1
kind: PersistentVolume # Create PV
metadata:
  name: postgres-volume # Sets PV name
  namespace: marketplace
  labels:
    type: local # Sets PV's type
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/data-nas/minikube # Sets PV's host path
